// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: api/proto/node.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeService_Ping_FullMethodName              = "/NodeService/Ping"
	NodeService_GetNextHop_FullMethodName        = "/NodeService/GetNextHop"
	NodeService_GetRoutingTable_FullMethodName   = "/NodeService/GetRoutingTable"
	NodeService_AddBackpointer_FullMethodName    = "/NodeService/AddBackpointer"
	NodeService_RemoveBackpointer_FullMethodName = "/NodeService/RemoveBackpointer"
	NodeService_NotifyMulticast_FullMethodName   = "/NodeService/NotifyMulticast"
	NodeService_Publish_FullMethodName           = "/NodeService/Publish"
	NodeService_Lookup_FullMethodName            = "/NodeService/Lookup"
	NodeService_Fetch_FullMethodName             = "/NodeService/Fetch"
	NodeService_Replicate_FullMethodName         = "/NodeService/Replicate"
	NodeService_NotifyLeave_FullMethodName       = "/NodeService/NotifyLeave"
)

// NodeServiceClient is the client API for NodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeServiceClient interface {
	Ping(ctx context.Context, in *Nothing, opts ...grpc.CallOption) (*Nothing, error)
	// Core Routing
	GetNextHop(ctx context.Context, in *RouteRequest, opts ...grpc.CallOption) (*RouteResponse, error)
	// Bootstrap & Maintenance
	GetRoutingTable(ctx context.Context, in *Nothing, opts ...grpc.CallOption) (*RTCopyResponse, error)
	AddBackpointer(ctx context.Context, in *BackpointerRequest, opts ...grpc.CallOption) (*Nothing, error)
	RemoveBackpointer(ctx context.Context, in *Neighbor, opts ...grpc.CallOption) (*Nothing, error)
	NotifyMulticast(ctx context.Context, in *MulticastRequest, opts ...grpc.CallOption) (*Nothing, error)
	// DOLR
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*Nothing, error)
	Lookup(ctx context.Context, in *LookupRequest, opts ...grpc.CallOption) (*LookupResponse, error)
	// Data Retrieval
	Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error)
	// Replication
	Replicate(ctx context.Context, in *ReplicateRequest, opts ...grpc.CallOption) (*Ack, error)
	// Graceful Exit
	NotifyLeave(ctx context.Context, in *Neighbor, opts ...grpc.CallOption) (*Nothing, error)
}

type nodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeServiceClient(cc grpc.ClientConnInterface) NodeServiceClient {
	return &nodeServiceClient{cc}
}

func (c *nodeServiceClient) Ping(ctx context.Context, in *Nothing, opts ...grpc.CallOption) (*Nothing, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Nothing)
	err := c.cc.Invoke(ctx, NodeService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetNextHop(ctx context.Context, in *RouteRequest, opts ...grpc.CallOption) (*RouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RouteResponse)
	err := c.cc.Invoke(ctx, NodeService_GetNextHop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetRoutingTable(ctx context.Context, in *Nothing, opts ...grpc.CallOption) (*RTCopyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RTCopyResponse)
	err := c.cc.Invoke(ctx, NodeService_GetRoutingTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) AddBackpointer(ctx context.Context, in *BackpointerRequest, opts ...grpc.CallOption) (*Nothing, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Nothing)
	err := c.cc.Invoke(ctx, NodeService_AddBackpointer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) RemoveBackpointer(ctx context.Context, in *Neighbor, opts ...grpc.CallOption) (*Nothing, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Nothing)
	err := c.cc.Invoke(ctx, NodeService_RemoveBackpointer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) NotifyMulticast(ctx context.Context, in *MulticastRequest, opts ...grpc.CallOption) (*Nothing, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Nothing)
	err := c.cc.Invoke(ctx, NodeService_NotifyMulticast_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*Nothing, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Nothing)
	err := c.cc.Invoke(ctx, NodeService_Publish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) Lookup(ctx context.Context, in *LookupRequest, opts ...grpc.CallOption) (*LookupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LookupResponse)
	err := c.cc.Invoke(ctx, NodeService_Lookup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchResponse)
	err := c.cc.Invoke(ctx, NodeService_Fetch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) Replicate(ctx context.Context, in *ReplicateRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, NodeService_Replicate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) NotifyLeave(ctx context.Context, in *Neighbor, opts ...grpc.CallOption) (*Nothing, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Nothing)
	err := c.cc.Invoke(ctx, NodeService_NotifyLeave_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServiceServer is the server API for NodeService service.
// All implementations must embed UnimplementedNodeServiceServer
// for forward compatibility.
type NodeServiceServer interface {
	Ping(context.Context, *Nothing) (*Nothing, error)
	// Core Routing
	GetNextHop(context.Context, *RouteRequest) (*RouteResponse, error)
	// Bootstrap & Maintenance
	GetRoutingTable(context.Context, *Nothing) (*RTCopyResponse, error)
	AddBackpointer(context.Context, *BackpointerRequest) (*Nothing, error)
	RemoveBackpointer(context.Context, *Neighbor) (*Nothing, error)
	NotifyMulticast(context.Context, *MulticastRequest) (*Nothing, error)
	// DOLR
	Publish(context.Context, *PublishRequest) (*Nothing, error)
	Lookup(context.Context, *LookupRequest) (*LookupResponse, error)
	// Data Retrieval
	Fetch(context.Context, *FetchRequest) (*FetchResponse, error)
	// Replication
	Replicate(context.Context, *ReplicateRequest) (*Ack, error)
	// Graceful Exit
	NotifyLeave(context.Context, *Neighbor) (*Nothing, error)
	mustEmbedUnimplementedNodeServiceServer()
}

// UnimplementedNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeServiceServer struct{}

func (UnimplementedNodeServiceServer) Ping(context.Context, *Nothing) (*Nothing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedNodeServiceServer) GetNextHop(context.Context, *RouteRequest) (*RouteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNextHop not implemented")
}
func (UnimplementedNodeServiceServer) GetRoutingTable(context.Context, *Nothing) (*RTCopyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoutingTable not implemented")
}
func (UnimplementedNodeServiceServer) AddBackpointer(context.Context, *BackpointerRequest) (*Nothing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBackpointer not implemented")
}
func (UnimplementedNodeServiceServer) RemoveBackpointer(context.Context, *Neighbor) (*Nothing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveBackpointer not implemented")
}
func (UnimplementedNodeServiceServer) NotifyMulticast(context.Context, *MulticastRequest) (*Nothing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyMulticast not implemented")
}
func (UnimplementedNodeServiceServer) Publish(context.Context, *PublishRequest) (*Nothing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedNodeServiceServer) Lookup(context.Context, *LookupRequest) (*LookupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Lookup not implemented")
}
func (UnimplementedNodeServiceServer) Fetch(context.Context, *FetchRequest) (*FetchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fetch not implemented")
}
func (UnimplementedNodeServiceServer) Replicate(context.Context, *ReplicateRequest) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Replicate not implemented")
}
func (UnimplementedNodeServiceServer) NotifyLeave(context.Context, *Neighbor) (*Nothing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyLeave not implemented")
}
func (UnimplementedNodeServiceServer) mustEmbedUnimplementedNodeServiceServer() {}
func (UnimplementedNodeServiceServer) testEmbeddedByValue()                     {}

// UnsafeNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServiceServer will
// result in compilation errors.
type UnsafeNodeServiceServer interface {
	mustEmbedUnimplementedNodeServiceServer()
}

func RegisterNodeServiceServer(s grpc.ServiceRegistrar, srv NodeServiceServer) {
	// If the following call pancis, it indicates UnimplementedNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeService_ServiceDesc, srv)
}

func _NodeService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Nothing)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).Ping(ctx, req.(*Nothing))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetNextHop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetNextHop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetNextHop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetNextHop(ctx, req.(*RouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetRoutingTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Nothing)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetRoutingTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetRoutingTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetRoutingTable(ctx, req.(*Nothing))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_AddBackpointer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackpointerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).AddBackpointer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_AddBackpointer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).AddBackpointer(ctx, req.(*BackpointerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_RemoveBackpointer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Neighbor)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).RemoveBackpointer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_RemoveBackpointer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).RemoveBackpointer(ctx, req.(*Neighbor))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_NotifyMulticast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MulticastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).NotifyMulticast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_NotifyMulticast_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).NotifyMulticast(ctx, req.(*MulticastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_Publish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_Lookup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).Lookup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_Lookup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).Lookup(ctx, req.(*LookupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_Fetch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).Fetch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_Fetch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).Fetch(ctx, req.(*FetchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_Replicate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).Replicate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_Replicate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).Replicate(ctx, req.(*ReplicateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_NotifyLeave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Neighbor)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).NotifyLeave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_NotifyLeave_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).NotifyLeave(ctx, req.(*Neighbor))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeService_ServiceDesc is the grpc.ServiceDesc for NodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "NodeService",
	HandlerType: (*NodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _NodeService_Ping_Handler,
		},
		{
			MethodName: "GetNextHop",
			Handler:    _NodeService_GetNextHop_Handler,
		},
		{
			MethodName: "GetRoutingTable",
			Handler:    _NodeService_GetRoutingTable_Handler,
		},
		{
			MethodName: "AddBackpointer",
			Handler:    _NodeService_AddBackpointer_Handler,
		},
		{
			MethodName: "RemoveBackpointer",
			Handler:    _NodeService_RemoveBackpointer_Handler,
		},
		{
			MethodName: "NotifyMulticast",
			Handler:    _NodeService_NotifyMulticast_Handler,
		},
		{
			MethodName: "Publish",
			Handler:    _NodeService_Publish_Handler,
		},
		{
			MethodName: "Lookup",
			Handler:    _NodeService_Lookup_Handler,
		},
		{
			MethodName: "Fetch",
			Handler:    _NodeService_Fetch_Handler,
		},
		{
			MethodName: "Replicate",
			Handler:    _NodeService_Replicate_Handler,
		},
		{
			MethodName: "NotifyLeave",
			Handler:    _NodeService_NotifyLeave_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/node.proto",
}
