// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: api/proto/node.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Nothing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nothing) Reset() {
	*x = Nothing{}
	mi := &file_api_proto_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nothing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nothing) ProtoMessage() {}

func (x *Nothing) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nothing.ProtoReflect.Descriptor instead.
func (*Nothing) Descriptor() ([]byte, []int) {
	return file_api_proto_node_proto_rawDescGZIP(), []int{0}
}

type NodeID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bytes         []byte                 `protobuf:"bytes,1,opt,name=bytes,proto3" json:"bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeID) Reset() {
	*x = NodeID{}
	mi := &file_api_proto_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeID) ProtoMessage() {}

func (x *NodeID) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeID.ProtoReflect.Descriptor instead.
func (*NodeID) Descriptor() ([]byte, []int) {
	return file_api_proto_node_proto_rawDescGZIP(), []int{1}
}

func (x *NodeID) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

type Neighbor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *NodeID                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"` // "IP:Port"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Neighbor) Reset() {
	*x = Neighbor{}
	mi := &file_api_proto_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Neighbor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Neighbor) ProtoMessage() {}

func (x *Neighbor) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Neighbor.ProtoReflect.Descriptor instead.
func (*Neighbor) Descriptor() ([]byte, []int) {
	return file_api_proto_node_proto_rawDescGZIP(), []int{2}
}

func (x *Neighbor) GetId() *NodeID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Neighbor) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type RoutingTableEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Neighbors     []*Neighbor            `protobuf:"bytes,1,rep,name=neighbors,proto3" json:"neighbors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutingTableEntry) Reset() {
	*x = RoutingTableEntry{}
	mi := &file_api_proto_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingTableEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingTableEntry) ProtoMessage() {}

func (x *RoutingTableEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingTableEntry.ProtoReflect.Descriptor instead.
func (*RoutingTableEntry) Descriptor() ([]byte, []int) {
	return file_api_proto_node_proto_rawDescGZIP(), []int{3}
}

func (x *RoutingTableEntry) GetNeighbors() []*Neighbor {
	if x != nil {
		return x.Neighbors
	}
	return nil
}

type RTCopyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*RoutingTableEntry   `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Rows          int32                  `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols          int32                  `protobuf:"varint,3,opt,name=cols,proto3" json:"cols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTCopyResponse) Reset() {
	*x = RTCopyResponse{}
	mi := &file_api_proto_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTCopyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTCopyResponse) ProtoMessage() {}

func (x *RTCopyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTCopyResponse.ProtoReflect.Descriptor instead.
func (*RTCopyResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_node_proto_rawDescGZIP(), []int{4}
}

func (x *RTCopyResponse) GetEntries() []*RoutingTableEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *RTCopyResponse) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *RTCopyResponse) GetCols() int32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

type MulticastRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewNode       *Neighbor              `protobuf:"bytes,1,opt,name=new_node,json=newNode,proto3" json:"new_node,omitempty"`
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MulticastRequest) Reset() {
	*x = MulticastRequest{}
	mi := &file_api_proto_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MulticastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MulticastRequest) ProtoMessage() {}

func (x *MulticastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MulticastRequest.ProtoReflect.Descriptor instead.
func (*MulticastRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_node_proto_rawDescGZIP(), []int{5}
}

func (x *MulticastRequest) GetNewNode() *Neighbor {
	if x != nil {
		return x.NewNode
	}
	return nil
}

func (x *MulticastRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type BackpointerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *Neighbor              `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackpointerRequest) Reset() {
	*x = BackpointerRequest{}
	mi := &file_api_proto_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackpointerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackpointerRequest) ProtoMessage() {}

func (x *BackpointerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackpointerRequest.ProtoReflect.Descriptor instead.
func (*BackpointerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_node_proto_rawDescGZIP(), []int{6}
}

func (x *BackpointerRequest) GetFrom() *Neighbor {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *BackpointerRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type RouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      *NodeID                `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	SourceId      *NodeID                `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteRequest) Reset() {
	*x = RouteRequest{}
	mi := &file_api_proto_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteRequest) ProtoMessage() {}

func (x *RouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteRequest.ProtoReflect.Descriptor instead.
func (*RouteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_node_proto_rawDescGZIP(), []int{7}
}

func (x *RouteRequest) GetTargetId() *NodeID {
	if x != nil {
		return x.TargetId
	}
	return nil
}

func (x *RouteRequest) GetSourceId() *NodeID {
	if x != nil {
		return x.SourceId
	}
	return nil
}

type RouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextHop       *Neighbor              `protobuf:"bytes,1,opt,name=next_hop,json=nextHop,proto3" json:"next_hop,omitempty"`
	IsRoot        bool                   `protobuf:"varint,2,opt,name=is_root,json=isRoot,proto3" json:"is_root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteResponse) Reset() {
	*x = RouteResponse{}
	mi := &file_api_proto_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteResponse) ProtoMessage() {}

func (x *RouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteResponse.ProtoReflect.Descriptor instead.
func (*RouteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_node_proto_rawDescGZIP(), []int{8}
}

func (x *RouteResponse) GetNextHop() *Neighbor {
	if x != nil {
		return x.NextHop
	}
	return nil
}

func (x *RouteResponse) GetIsRoot() bool {
	if x != nil {
		return x.IsRoot
	}
	return false
}

type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      *NodeID                `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	Publisher     *Neighbor              `protobuf:"bytes,2,opt,name=publisher,proto3" json:"publisher,omitempty"`
	HopLimit      int32                  `protobuf:"varint,3,opt,name=hop_limit,json=hopLimit,proto3" json:"hop_limit,omitempty"` // Required to prevent infinite loops
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_api_proto_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_node_proto_rawDescGZIP(), []int{9}
}

func (x *PublishRequest) GetObjectId() *NodeID {
	if x != nil {
		return x.ObjectId
	}
	return nil
}

func (x *PublishRequest) GetPublisher() *Neighbor {
	if x != nil {
		return x.Publisher
	}
	return nil
}

func (x *PublishRequest) GetHopLimit() int32 {
	if x != nil {
		return x.HopLimit
	}
	return 0
}

type LookupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      *NodeID                `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	HopLimit      int32                  `protobuf:"varint,2,opt,name=hop_limit,json=hopLimit,proto3" json:"hop_limit,omitempty"` // Required to prevent infinite loops
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupRequest) Reset() {
	*x = LookupRequest{}
	mi := &file_api_proto_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupRequest) ProtoMessage() {}

func (x *LookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupRequest.ProtoReflect.Descriptor instead.
func (*LookupRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_node_proto_rawDescGZIP(), []int{10}
}

func (x *LookupRequest) GetObjectId() *NodeID {
	if x != nil {
		return x.ObjectId
	}
	return nil
}

func (x *LookupRequest) GetHopLimit() int32 {
	if x != nil {
		return x.HopLimit
	}
	return 0
}

type LookupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Publisher     *Neighbor              `protobuf:"bytes,1,opt,name=publisher,proto3" json:"publisher,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupResponse) Reset() {
	*x = LookupResponse{}
	mi := &file_api_proto_node_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupResponse) ProtoMessage() {}

func (x *LookupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_node_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupResponse.ProtoReflect.Descriptor instead.
func (*LookupResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_node_proto_rawDescGZIP(), []int{11}
}

func (x *LookupResponse) GetPublisher() *Neighbor {
	if x != nil {
		return x.Publisher
	}
	return nil
}

func (x *LookupResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type FetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	mi := &file_api_proto_node_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_node_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_node_proto_rawDescGZIP(), []int{12}
}

func (x *FetchRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type FetchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchResponse) Reset() {
	*x = FetchResponse{}
	mi := &file_api_proto_node_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchResponse) ProtoMessage() {}

func (x *FetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_node_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchResponse.ProtoReflect.Descriptor instead.
func (*FetchResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_node_proto_rawDescGZIP(), []int{13}
}

func (x *FetchResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *FetchResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

var File_api_proto_node_proto protoreflect.FileDescriptor

const file_api_proto_node_proto_rawDesc = "" +
	"\n" +
	"\x14api/proto/node.proto\"\t\n" +
	"\aNothing\"\x1e\n" +
	"\x06NodeID\x12\x14\n" +
	"\x05bytes\x18\x01 \x01(\fR\x05bytes\"=\n" +
	"\bNeighbor\x12\x17\n" +
	"\x02id\x18\x01 \x01(\v2\a.NodeIDR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"<\n" +
	"\x11RoutingTableEntry\x12'\n" +
	"\tneighbors\x18\x01 \x03(\v2\t.NeighborR\tneighbors\"f\n" +
	"\x0eRTCopyResponse\x12,\n" +
	"\aentries\x18\x01 \x03(\v2\x12.RoutingTableEntryR\aentries\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\x05R\x04rows\x12\x12\n" +
	"\x04cols\x18\x03 \x01(\x05R\x04cols\"N\n" +
	"\x10MulticastRequest\x12$\n" +
	"\bnew_node\x18\x01 \x01(\v2\t.NeighborR\anewNode\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\"I\n" +
	"\x12BackpointerRequest\x12\x1d\n" +
	"\x04from\x18\x01 \x01(\v2\t.NeighborR\x04from\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\"Z\n" +
	"\fRouteRequest\x12$\n" +
	"\ttarget_id\x18\x01 \x01(\v2\a.NodeIDR\btargetId\x12$\n" +
	"\tsource_id\x18\x02 \x01(\v2\a.NodeIDR\bsourceId\"N\n" +
	"\rRouteResponse\x12$\n" +
	"\bnext_hop\x18\x01 \x01(\v2\t.NeighborR\anextHop\x12\x17\n" +
	"\ais_root\x18\x02 \x01(\bR\x06isRoot\"|\n" +
	"\x0ePublishRequest\x12$\n" +
	"\tobject_id\x18\x01 \x01(\v2\a.NodeIDR\bobjectId\x12'\n" +
	"\tpublisher\x18\x02 \x01(\v2\t.NeighborR\tpublisher\x12\x1b\n" +
	"\thop_limit\x18\x03 \x01(\x05R\bhopLimit\"R\n" +
	"\rLookupRequest\x12$\n" +
	"\tobject_id\x18\x01 \x01(\v2\a.NodeIDR\bobjectId\x12\x1b\n" +
	"\thop_limit\x18\x02 \x01(\x05R\bhopLimit\"O\n" +
	"\x0eLookupResponse\x12'\n" +
	"\tpublisher\x18\x01 \x01(\v2\t.NeighborR\tpublisher\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\" \n" +
	"\fFetchRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"9\n" +
	"\rFetchResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found2\x88\x03\n" +
	"\vNodeService\x12\x1a\n" +
	"\x04Ping\x12\b.Nothing\x1a\b.Nothing\x12+\n" +
	"\n" +
	"GetNextHop\x12\r.RouteRequest\x1a\x0e.RouteResponse\x12,\n" +
	"\x0fGetRoutingTable\x12\b.Nothing\x1a\x0f.RTCopyResponse\x12/\n" +
	"\x0eAddBackpointer\x12\x13.BackpointerRequest\x1a\b.Nothing\x12(\n" +
	"\x11RemoveBackpointer\x12\t.Neighbor\x1a\b.Nothing\x12.\n" +
	"\x0fNotifyMulticast\x12\x11.MulticastRequest\x1a\b.Nothing\x12$\n" +
	"\aPublish\x12\x0f.PublishRequest\x1a\b.Nothing\x12)\n" +
	"\x06Lookup\x12\x0e.LookupRequest\x1a\x0f.LookupResponse\x12&\n" +
	"\x05Fetch\x12\r.FetchRequest\x1a\x0e.FetchResponseB\x14Z\x12tapestry/api/protob\x06proto3"

var (
	file_api_proto_node_proto_rawDescOnce sync.Once
	file_api_proto_node_proto_rawDescData []byte
)

func file_api_proto_node_proto_rawDescGZIP() []byte {
	file_api_proto_node_proto_rawDescOnce.Do(func() {
		file_api_proto_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_node_proto_rawDesc), len(file_api_proto_node_proto_rawDesc)))
	})
	return file_api_proto_node_proto_rawDescData
}

var file_api_proto_node_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_proto_node_proto_goTypes = []any{
	(*Nothing)(nil),            // 0: Nothing
	(*NodeID)(nil),             // 1: NodeID
	(*Neighbor)(nil),           // 2: Neighbor
	(*RoutingTableEntry)(nil),  // 3: RoutingTableEntry
	(*RTCopyResponse)(nil),     // 4: RTCopyResponse
	(*MulticastRequest)(nil),   // 5: MulticastRequest
	(*BackpointerRequest)(nil), // 6: BackpointerRequest
	(*RouteRequest)(nil),       // 7: RouteRequest
	(*RouteResponse)(nil),      // 8: RouteResponse
	(*PublishRequest)(nil),     // 9: PublishRequest
	(*LookupRequest)(nil),      // 10: LookupRequest
	(*LookupResponse)(nil),     // 11: LookupResponse
	(*FetchRequest)(nil),       // 12: FetchRequest
	(*FetchResponse)(nil),      // 13: FetchResponse
}
var file_api_proto_node_proto_depIdxs = []int32{
	1,  // 0: Neighbor.id:type_name -> NodeID
	2,  // 1: RoutingTableEntry.neighbors:type_name -> Neighbor
	3,  // 2: RTCopyResponse.entries:type_name -> RoutingTableEntry
	2,  // 3: MulticastRequest.new_node:type_name -> Neighbor
	2,  // 4: BackpointerRequest.from:type_name -> Neighbor
	1,  // 5: RouteRequest.target_id:type_name -> NodeID
	1,  // 6: RouteRequest.source_id:type_name -> NodeID
	2,  // 7: RouteResponse.next_hop:type_name -> Neighbor
	1,  // 8: PublishRequest.object_id:type_name -> NodeID
	2,  // 9: PublishRequest.publisher:type_name -> Neighbor
	1,  // 10: LookupRequest.object_id:type_name -> NodeID
	2,  // 11: LookupResponse.publisher:type_name -> Neighbor
	0,  // 12: NodeService.Ping:input_type -> Nothing
	7,  // 13: NodeService.GetNextHop:input_type -> RouteRequest
	0,  // 14: NodeService.GetRoutingTable:input_type -> Nothing
	6,  // 15: NodeService.AddBackpointer:input_type -> BackpointerRequest
	2,  // 16: NodeService.RemoveBackpointer:input_type -> Neighbor
	5,  // 17: NodeService.NotifyMulticast:input_type -> MulticastRequest
	9,  // 18: NodeService.Publish:input_type -> PublishRequest
	10, // 19: NodeService.Lookup:input_type -> LookupRequest
	12, // 20: NodeService.Fetch:input_type -> FetchRequest
	0,  // 21: NodeService.Ping:output_type -> Nothing
	8,  // 22: NodeService.GetNextHop:output_type -> RouteResponse
	4,  // 23: NodeService.GetRoutingTable:output_type -> RTCopyResponse
	0,  // 24: NodeService.AddBackpointer:output_type -> Nothing
	0,  // 25: NodeService.RemoveBackpointer:output_type -> Nothing
	0,  // 26: NodeService.NotifyMulticast:output_type -> Nothing
	0,  // 27: NodeService.Publish:output_type -> Nothing
	11, // 28: NodeService.Lookup:output_type -> LookupResponse
	13, // 29: NodeService.Fetch:output_type -> FetchResponse
	21, // [21:30] is the sub-list for method output_type
	12, // [12:21] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_api_proto_node_proto_init() }
func file_api_proto_node_proto_init() {
	if File_api_proto_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_node_proto_rawDesc), len(file_api_proto_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_node_proto_goTypes,
		DependencyIndexes: file_api_proto_node_proto_depIdxs,
		MessageInfos:      file_api_proto_node_proto_msgTypes,
	}.Build()
	File_api_proto_node_proto = out.File
	file_api_proto_node_proto_goTypes = nil
	file_api_proto_node_proto_depIdxs = nil
}
